# -*- coding: utf-8 -*-
"""inf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjZ8eDah2wyiR3IkecfDc43ouP2Nr-sG
"""

import torch
import torchvision.models as models
model_path = "/home/aymen/Downloads/g.pt"
model = torch.load(model_path)
model.eval()
fixed_latent = torch.randn(128, latent_size, 1, 1, device=device)
output = model(input_tensor)

